spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://my_db:3306/bankapp?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    drop-first: true
server:
  port: 8081
  servlet:
    context-path: /api

